travis:
  secure:
    BINSTAR_TOKEN: VYPiqrxnP9nCsQ4X5DX3/lWtOOjxVaXB8aUW3BzTB7j4KbS6g2ogaC5TdVK+Pc0d0q9zR+gg1uHJYzSU8oFp0+7Acd/Yn+K9oBmDWpE2AM90OBRSxqS1SbtJPODN07f04tO+4tV1j6Rym8lhwRs8EfT+daJNQ8yD18CEDW6Pxa6SvY05OKhcutlIT2Dv2Xg0BJtlf0hW5DRq+NalfFmJGQlSg6okwldzZtaSY5FsP60FFH357BBEThVvTQvmUgcITNrALPr+fsLfawKo2qD6O0X8TSYIUIqJsRMCG+yFhP1D7fyZAreEHeIA3eu8U5+yOfNA9cgFdN0DHza+MiYxQ630PZyVk3lwmEBljvq/xAyQt3nse/sklwtGgVtj7T4Vs0/fQojH2f/PRYaSCl4srBxpcPjgWXvT7NAZsYAdcrQX37GzXJIT07bD5CM0QKL7PbCv2NJIoMRPVz4PJMU+QpAT+gyWLsYfN26lGqdvuOMwm2zCnO3zBsg+Huy+HnIQDDodhJRU4545YERCLJ7jwHGv9WyadUjw78YJx34ZdhpmGa0xG7QZGUcp40dhxbxul7CFGR2Sr8RE0WATLvncuOD2iqta2eRpQ9eMIUD6YU93Q2AwdX58J4yveghOoQykE5vW7/C76DfVJVNXFdTTZvKwzpkcpwPcRcLFLZFdNrQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
