travis:
  secure:
    BINSTAR_TOKEN: ErbuO2cZGt+ZORyWbxDIUc5otWeUssrcn+xJlwaRP/Dhp1+GpGZ/4ifA/npvrHxG2wXPQThir+kLocsfOVMqururExUxeJ3VTiUEkuXV77pKXG2W9EEPLrqPfcWM2arktprW/xJuN3sr79pVqFc86fodPaYmeC7bhj5GWD4/iMWBkDxiPt6a63LBkXBkUTlC+FLq8D/uy84fM2JNnazajrn6JEOT+CNoi34+st0Ilnml5m1KLZxn+dD43/PeY8+fNVETfgCYxI5DUB7VchjKDAPRnT6XEevQcXBg+w+vOoZNvo8XnV8n/D+PeQ7XTlUWB1VYRCMCzqptxOP92KjeUAiQRWsTEnkwMIWvd+GrLXeUhTobZRkzzVaPymC5nkzdRXK/CJKBUJMve11bm3unDQhVddgykN1p3GTo01+VUYW7XSK1rnJoAHuw9Efrt2piE8RsMu8BoBOz37GMz7EudLdPJQ7kcMcX7aXTywpTR24kkFqOSBJNLGDZBrx9OQCxMLxlLOWRmZKrm5CzDqelluidAXv86iUEqRof4hu9rmDBbPbOD/z1FQ8SqkxWdpRHrNgcn9ou9vj/hcYfQ64cFVs9hVVfINDXwsxrMkxR5z6T05Qz0PBmYqwIe9ItFyvCoK5h0YYFVrcCwR7PYg5PXpDYiEVMeNpCEdSNArmWEOc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
